// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class SurvivalCubeResources
{
        public const string achievement_same_but_different = "CgkI2M_Y7rYQEAIQAw"; // <GPGSID>
        public const string achievement_locked_and_loaded = "CgkI2M_Y7rYQEAIQDg"; // <GPGSID>
        public const string leaderboard_topplayers = "CgkI2M_Y7rYQEAIQBg"; // <GPGSID>
        public const string achievement_loose_cannon = "CgkI2M_Y7rYQEAIQCg"; // <GPGSID>
        public const string achievement_triple_the_threat = "CgkI2M_Y7rYQEAIQAg"; // <GPGSID>
        public const string achievement_here_they_come_again = "CgkI2M_Y7rYQEAIQCw"; // <GPGSID>
        public const string achievement_technomurderer = "CgkI2M_Y7rYQEAIQDA"; // <GPGSID>
        public const string achievement_sweep_the_legs = "CgkI2M_Y7rYQEAIQDQ"; // <GPGSID>
        public const string achievement_the_adventure_begins = "CgkI2M_Y7rYQEAIQAQ"; // <GPGSID>
        public const string achievement_robot_genocide = "CgkI2M_Y7rYQEAIQCA"; // <GPGSID>
        public const string achievement_getting_tired_of__resurrecting_you = "CgkI2M_Y7rYQEAIQBA"; // <GPGSID>
        public const string achievement_robot_apocalypse = "CgkI2M_Y7rYQEAIQCQ"; // <GPGSID>
        public const string achievement_mayhem = "CgkI2M_Y7rYQEAIQBw"; // <GPGSID>
        public const string achievement_electroshock_therapy = "CgkI2M_Y7rYQEAIQBQ"; // <GPGSID>

}

